# Generated by Django 3.2.8 on 2022-03-30 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='altText',
        ),
        migrations.RemoveField(
            model_name='image',
            name='landImage',
        ),
        migrations.RemoveField(
            model_name='image',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='image',
            name='tallImage',
        ),
    ]
