# Generated by Django 3.2.8 on 2022-03-30 18:08

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220330_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='squareImage',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='default_square.jpg', force_format=None, keep_meta=True, quality=75, size=[1000, 1000], upload_to='square'),
        ),
    ]
