# Generated by Django 3.2.8 on 2022-03-30 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_image_madeby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='madeBy',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
