# Generated by Django 3.2.8 on 2022-04-05 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_geeksmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GeeksModel',
        ),
        migrations.RemoveField(
            model_name='image',
            name='date_created',
        ),
    ]
