# Generated by Django 3.2.8 on 2022-04-05 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_image_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='date_created',
        ),
    ]
